# Generated by Django 5.1 on 2025-01-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("gas_leakage", "Gas Leakage"),
                            ("billing_issue", "Billing Issue"),
                            ("pipe_leakage", "Pipe Leakage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
