# Generated by Django 5.1 on 2025-01-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="service_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("resolved", "Resolved")],
                max_length=20,
            ),
        ),
    ]
