# Generated by Django 5.1 on 2025-01-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_servicerequest_attachment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequest",
            name="created_at",
        ),
    ]
